name: CloudSim v1 Workflow

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Build with Maven
      run: mvn -B package -DskipTests
      
    - name: Test
      run: mvn test
    
    - name: Run simulation
      run: |
        cd modules/cloudsim-examples
        java -cp ".:../cloudsim/target/classes:target/classes" org.cloudbus.cloudsim.examples.AutoScaling 